name = "Winter 24"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93ff342b8aff3bafbd230932579ad1b9607bd999ef10c01450398c3b4fea1ccc"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
