name = "Winter 24"
version = "0.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "082c3add2e3de8fe93c8637406aec2cf729d11f4d1e16f38048a290a07958d4b"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
