name = "Winter 24"
version = "0.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04b95fdbdf35827d20f21fde1babd0cd96fc3b5484eb3f1a6aa9ae9422542bda"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
