name: Build Pack

on:
  - push
  - pull_request

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actionhippie/install-packwiz@v1

      - run: packwiz cf export --side server --output server.zip
      - run: packwiz cf export --side client --output client.zip

      - uses: actions/upload-artifact@v4
        with:
          name: client.zip
          path: client.zip

      - uses: actions/upload-artifact@v4
        with:
          name: server.zip
          path: server.zip
