name: Build Pack

on:
  - push
  - pull_request

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actionhippie/install-packwiz@v1

      - run: mkdir -p "${{ runner.temp }}/cache/import" && cp manual-downloads/* "${{ runner.temp }}/cache/import/"

      - run: packwiz cf export --side server --output server.zip
      - run: unzip server.zip -d server
      - uses: actions/upload-artifact@v4
        with:
          name: server
          path: server

      - run: packwiz cf export --side client --output client.zip
      - run: unzip client.zip -d client 
      - uses: actions/upload-artifact@v4
        with:
          name: client
          path: client

      - run: packwiz mr export --cache "${{ runner.temp}}/cache" --output jars.zip
      - run: unzip jars.zip -d jars
      - uses: actions/upload-artifact@v4
        with:
          name: jars
          path: jars

      - run: packwiz cf export --side both --output both.zip
      - run: unzip both.zip -d both 
      - uses: actions/upload-artifact@v4
        with:
          name: both
          path: both

